apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-primeiro
  labels:
    app: Giropops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Giropops
  template:
    metadata:
      name: Giropops
      labels:
        app: Giropops
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
